layout: default
title: Guillermo Fernando Puiggros
description: Developer & IT Enthusiast, Electromechanical Enginner 
site_title: '@Guillermo - Guillermo Puiggros'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: GuillermoFernandoPuiggros
blog_url: https://guillermofernandopuiggros.github.io/
email: gfpuiggros@gmail.com
linkedin_username: www.linkedin.com/in/guillermo-puiggros

# absolute or relative
profile_picture: /assets/images/fotopersonal.jpg

# Google Analytics ID
#google_analytics: # UA-XXXXXXXXX-X (opcional, agregar despu√©s)